name: Main

on: push

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_docker:
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Build docker images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create short version name
        id: short_version
        run: |
          version=$(echo "${{ github.ref_name }}" | sed 's/\.[0-9]*$//g')
          echo "value=$version" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        env:
          IMAGE_PATH: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_VERSION: ${{ github.ref_name }}
          IMAGE_VERSION_SHORT: ${{ steps.short_version.outputs.value }}
        run: |
          chmod +x ./builder/build.sh
          ./builder/build.sh
